-- -- Function to enable auto-centering in terminal buffers
-- local function enable_auto_center()
-- 	vim.api.nvim_create_autocmd({ "BufWinEnter", "WinScrolled", "TermEnter" }, {
-- 		pattern = "term://*",
-- 		callback = function()
-- 			vim.cmd("normal! Gzz")
-- 		end,
-- 	})
-- end
--
-- -- Call the function to enable the auto-centering feature
-- enable_auto_center()
